name: Build and test Go
on: [push, pull_request]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goVer: ["1.11", "1.12", "1.13" ,"1.15"]
    steps:
      - name: Set up Go ${{ matrix.goVer }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.goVer }}

      - name: Check out source code
        uses: actions/checkout@v1

      - name: Cache Go modules
        uses: actions/cache@preview
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go build .

      - name: Test
        env:
          GOPROXY: "https://proxy.golang.org"
        run: make test